### ISSUE TITLE
Error in font selection

### ISSUE THREAD

**Issue by electro7** [LemonBoy/bar#101]
First, sorry for my english. :P

I found a error in the pacth of multiple fonts (pull request #98) . If only pass two fonts, the %{T2} tag don´t work. For example:

echo "hello%{T2}bye" | bar -p -f "font1,font2"

If pass three fonts, the %{T2} tag works, but %{T3} don´t. I think the problem is in the base 1-index, that makes the last font in the list can not be used.

**Comment by LemonBoy** [comment]
The latest commit should fix it! Thanks for noticing and reporting the bug :dancer:
