### ISSUE TITLE
bar in PPC, is possible?

### ISSUE THREAD

**Issue by electro7** [LemonBoy/bar#103]
Hi.

First, thanks for this piece of software. Finally I found a alternative for the old dzen2. :)

I have a sucessfull bar running in debian wheezy on a i686 machine, but my problem is with an old powerbook laptop (old, but very hard) with the same linux distribution. The last commit  compile without problems, but when I run the simple "echo test | bar -p -d" nothing happens, nothing appears, but alfter few seconds the cpu load reach the 100%.

I try to debug the bar process and a infinite loop occurs calling libxcb. Any idea or suggestion to solve the problem? 

Yes, I know the difficult to solve a problem with a different architecture, but maybe any idea can help.

Sorry for my bad english.

**Comment by LemonBoy** [comment]
This might be slightly hard to debug heh, can you give some more details about the point where xcb hangs ?

**Comment by electro7** [comment]
Well, I found the "problem". The infinite loop occurs in line 1138, in the function getopt. I solve adding a cast in the "!= -1" comparison.

char ch;
while ((ch = getopt(argc, argv, "hg:bdf:a:pu:B:F:")) != (char) -1) {

In PPC seems the typecast is very necessary. :)

It works now, but I have a problem with the fonts. All the fonts I test, are squares. xDD

![2015-02-13-080941_1024x768_scrot](https://cloud.githubusercontent.com/assets/10460174/6183801/3742d9fe-b35a-11e4-8af3-a83561a30c90.png)

I will continue testing to see if I can find the problem with drawing fonts.

**Comment by LemonBoy** [comment]
That's probably because of the different endianness, you should tinker with the parts that assume the host to be little endian (eg. The part where 'ch' is rotated)

**Comment by mrshankly** [comment]
Shouldn't `ch` be an `int` all along? `getopt()` returns `int` after all.

Your tool chain in PPC probably uses unsigned for `char`, when `getopt()` returns -1 the value stored in `ch` will be 255, which obviously passes the check `!= -1`.

**Comment by jvvv** [comment]
Yep, ch should be int. Kicking myself for not noticing it sooner.

**Comment by LemonBoy** [comment]
Eww, signedness issues are hard to catch :D
Anyway the latest commit replaces most of the color-related bit twiddling with some nicer code, it'd be nice to make it work on BE hosts too :>

**Comment by mrshankly** [comment]
I think I have a big-endian machine lying around, if so I can have a further look into this. I can only start next week though.

**Comment by mrshankly** [comment]
Ok, next week came earlier lol.

@electro7, can you test this [branch](https://github.com/mrshankly/bar/tree/big-endian) please? I tested it on a big-endian machine and on a powerpc emulated with qemu and it worked on both.

@LemonBoy, I'm not submitting a pull request because I don't know how do you want to implement this. The culprit is [this line](https://github.com/LemonBoy/bar/blob/1ef64eab99b914c293e9c2a9241c3439af0a21ef/bar.c#L212), it assumes that the host architecture is always little-endian. I used `htobe16()` which will work on both LE and BE, but the header file is different on BSDs, Linux and probably on Mac OS too. I'm not sure what the best approach is here.

Also, the `rgba_t` union is wrong on both LE and BE. On little-endian it should be:

```c
typedef union rgba_t {
    struct {
        uint8_t b;
        uint8_t g;
        uint8_t r;
        uint8_t a;
    };
    uint32_t v;
} rgba_t;
```

and on big-endian:

```c
typedef union rgba_t {
    struct {
        uint8_t a;
        uint8_t r;
        uint8_t g;
        uint8_t b;
    };
    uint32_t v;
} rgba_t;
```

The `v` field on little-endian ends up with the correct value and the colors are correct because of that I guess, but the `r` and `b` fields are switched. Maybe the best thing to do here is to not use a union at all since these can be tricky with endianness.

**Comment by LemonBoy** [comment]
Good catch, you've just seen that the old proverb "two wrong make a right" is true :)
The union is a nice way to mess with the byte values without having to clutter the code with shifts and masks, a simple #ifdef BE is enough to keep BE and LE machines happy.
With the same trick `htobe`k could be replaced with __builtin_bswap16.

**Comment by electro7** [comment]
It's work like a charm. 

I'm test in a G5 powermac and a G4 powerbook and work's perfect in both. Test some fonts and color, no problem.

Thanks for the effort. :P

**Comment by mrshankly** [comment]
Is there a standard way to check for endianness at compile-time? I can't seem to find one. All the options I've found either limit yourself to a compiler or fail on some architectures.

**Comment by LemonBoy** [comment]
There's no standard way to detect endianness at compile time other than resorting to nasty tricks involving casting a byte sequence to an integer type and check the order afterwards

**Comment by electro7** [comment]
Hi. I found this for check the endiannes:

```c
#define BIG_ENDIAN      0
#define LITTLE_ENDIAN   1

int TestByteOrder()
{
   short int word = 0x0001;
   char *byte = (char *) &word;
   return(byte[0] ? LITTLE_ENDIAN : BIG_ENDIAN);
}
````
This code assigns the value 0001h to a 16-bit integer. A char pointer is then assigned to point at the first (least-significant) byte of the integer value. If the first byte of the integer is 0x01h, then the system is Little-Endian (the 0x01h is in the lowest, or least-significant, address). If it is 0x00h then the system is Big-Endian.

Found here -> http://www.codeproject.com/Articles/4804/Basic-concepts-on-Endianness

**Comment by electro7** [comment]
Ok. The question was "check for endianness at COMPILE-TIME?" My fault, sorry.

GNU C library provide a header named <endian.h> containing macros for check endiannes. Here is commented -> http://sourceforge.net/p/predef/wiki/Endianness/

**Comment by LemonBoy** [comment]
Any update on this ? I'd like to do a point release sometimes soon and endian-neutrality would be a cool feature to put in the changelog :)

**Comment by LemonBoy** [comment]
Closing this as many moons have passed.
