### ISSUE TITLE
Background color not rendering properly(offset by +y argument)

### ISSUE THREAD

**Issue by neeasade** [LemonBoy/bar#108]
The background color that I set gets offset by the same amount of pixels I set in my y offset. 

[here](http://a.pomf.se/pbrlfc.png) is what I see on one of my monitors when I have the bar set with the following command(the +8 is the relevant part):

bar -g 1904x20x1088+8 -f -*-tewi-medium-*-*-*-*-*-*-*-*-*-*-* -F #ffc5c8c6 -B ff1d1f21
  
and the workspace section in the image is prefixed with "%{B#FF373B41}".

The weird thing is, when run with no y offset, bar renders the background color at [full height](http://a.pomf.se/lqyzbx.png), as I would expect it to do. 

this problem persists regardless of bar height.

**Comment by LemonBoy** [comment]
The latest commit should fix the problem. It was discovered by another user ~1 year ago but got no response after the initial report, It turns out it was just a silly error :)

**Comment by neeasade** [comment]
Wow that was fast! Thanks that fixed it! I had spent the past hour going over things paranoid I was doing this on purpose somewhere. 

Awesome.
