### ISSUE TITLE
palette.pl only works with specific formatting

### ISSUE THREAD

**Issue by JSchilli1** [LemonBoy/bar#111]
I've noticed that the palette.pl script doesn't work correctly when the formatting of the Xresources file is like so:

`*.foreground: #xxyyzz`

It only works like this:

`*foreground: #xxyyzz`

It's kind of a nitpick, but terminal.sexy uses this style of naming and figured you'd want to be aware of it, as some people (including me) use it to create their schemes.

**Comment by LemonBoy** [comment]
I'm confused, that script isn't useful anymore since bar moved away from the compiled-in colour schemes

**Comment by JSchilli1** [comment]
Yeah, I've figured that out since. Thanks anyways. Maybe you could remove palette.pl from the repo to prevent confusion?
