### ISSUE TITLE
Bug when using different resolutions on two monitors

### ISSUE THREAD

**Issue by Ploppz** [LemonBoy/bar#112]
My monitors are called DVI-0 and HDMI-0. They are both `1920x1080`, but I wanted to rotate one of them by 90 degrees. Thus, I called this `xrandr` command:
```
xrandr --output DVI-0 --auto --rotate left --output HDMI-0 --auto --right-of DVI-0
```

DVI-0 is "standing" (height > width), and is left of HDMI-0. I tried to run bar on first my left (rotated) monitor, then my right one. The results are:
* left: the bar seems to be 1920 pixels wide, which is incorrect, as it should be 1080 pixels wide: http://a.pomf.se/cxbndl.png
* right: the bar seems to be 1080 pixel wide, which is incorrect, as it should be 1920 pixels wide: http://a.pomf.se/wwvqhh.png

Edit: And here, I have rotated both screens. The bar almost does not show. In this picture, I set the monitor to the right-most one. If I set it to the left-most one, I get the same result as earlier (it overflows and continues into monitor 2).

**Comment by jvvv** [comment]
the bar command line you are using?

**Comment by Ploppz** [comment]
```
cat "$PANEL_FIFO" | layout | bar -B '#00000000' -f "*terminus*,*stlphallus*" & PANEL_PID=$!
```

And in layout, I put the contents of the bar in a string `str`, and switched between `echo "%{S0}$str"` and `echo "%{S1}$str"`

Anyhow, I just changed my monitor set up so that the left-most one is now normal 1920x1080, and the right-most one is rotated 90 degrees. Doing the same tests again, it all works properly now. It might be worth looking into though maybe, as there is a flaw somewhere.

**Comment by LemonBoy** [comment]
My best guess is that the code that swapped the width/height when RandR reported the monitor to be rotated should come back

**Comment by jvvv** [comment]
This sounds like there is an issue with getting the correct width/height info attached to the correct monitor. I will work on replicating this, Could we hold off on adding the swapping code back in for a bit while I do some testing?

**Comment by jvvv** [comment]
I can't reproduce this using git master at HEAD commit. I'm a bit curious about a number of things: what version (git commit) of bar are you running? are you calling xrandr before or after starting bar? what is the output of `xrandr -q`? This would help me greatly in trying to track down the issue.

**Comment by Ploppz** [comment]
Ah, that's a fair point, it might be several months old. I just re-installed it from the AUR, and tried to reproduce, and indeed, there is no problem in the newest version. Sorry about that.

**Comment by jvvv** [comment]
I just want to say thanks for following up. It's no problem for me, looking into these issues whether or not they turn out to be a bug or not. But I truly appreciate that you stuck it out and were very prompt reporting back.
