### ISSUE TITLE
[faeturerequest] vertical bar

### ISSUE THREAD

**Issue by suptimal** [LemonBoy/bar#113]
add a vertical feature pls

**Comment by sLLiK** [comment]
This already seems possible on a basic level to my initial testing, as I literally came here to search and find if my problem was already opened as an issue, and it's related to your request.  

I've been able to create a vertical bar by modifying the values of the panel script.  In the invocation of lemonbar itself, if I set $PANEL_HEIGHT="230x1080", it will give me a vertical bar 230 pixels wide and 1080 pixels tall.  There's two problems with this, however.  FIrstly, your list of desktops will span the entire height, which is probably not what you want.  And second, there's apparently no way to get it to move to the right side if that's you're wish - it seems to be stuck at left-justified.  You have to add the -b flag for it to work at all, and the x and y arguments seem to be ignored.  

In my particular case, I created a second panel (aka panel2 and panel2_bar), with the intention of running a normal lemonbar at the top and a secondary vertical instance containing additional information.  The drawback to this is that there's (so far) no obvious way to disable the redundant (and overly-large, in this case) list of desktops.  I may be missing a setting, though.  I'll keep digging.

**Comment by sLLiK** [comment]
In hindsight, despite the minimal left-side success, there's not much to be done with it as far as I can tell because there's no multiline support.  So until the below feature is considered, the issue's moot:

https://github.com/LemonBoy/bar/issues/107
