### ISSUE TITLE
Clickable areas not working

### ISSUE THREAD

**Issue by mfin** [LemonBoy/bar#114]
I've been trying to add clickable areas to my panel, but so far, I've had no success. Are there any dependencies I should know about?

    echo "$SEP %{A:cmus-remote --pause:}$(printf '%b' "\ue059")%{A} %{A:cmus-remote --next:}$(printf '%b' "\ue05a")%{A} %{F$COLOR2}$(printf '%b' "\ue05c")%{F-} $ARTIST - $TITLE"

This is the line I'm using to gather some info and make it clickable.

**Comment by otommod** [comment]
If you are expecting to execute `cmus-remote --pause` when you click, you'd have to pipe `bar` to `sh`.  All that `bar` does is print the "action" to it's stdout when you click the area.

**Comment by mfin** [comment]
Oh my god, I'm so stupid. FWIW, the OUTPUT section in readme should be moved to Abutton:command: section. :)

Fixed!
