### ISSUE TITLE
How to pipe attributes from conky-cli?

### ISSUE THREAD

**Issue by joetemp** [LemonBoy/bar#115]
I'm trying to pipe just a few items from conky-cli and I'm running into trouble. Can you give me any pointers? Thanks!

**Comment by Stebalien** [comment]
What have you tried?

**Comment by joetemp** [comment]
Check this out:

http://pastebin.com/MaYeTN5e

I'm trying to add conky to a named pipe called $PANEL_FIFO. Then, I'm piping that to lemonbar... but it's not working. I know it's possible and I know I'm probably making  a stupid mistake. Any help is greatly appreciated. Thanks!

**Comment by otommod** [comment]
@joetemp When using regular conky and trying this example conkyrc
```
out_to_console yes
update_interval 1

TEXT
${time %D %H:%M:%S}
```
like this `conky | bar`, the bar only updates when I'm looking at the conky window.
When I add `out_to_x no` at the top of the conkyrc though, it works as expected.
