### ISSUE TITLE
mplus japanese font not showing characters correctly

### ISSUE THREAD

**Issue by reportados123** [LemonBoy/bar#116]
Hi. for some reason when using mplus fonts, the hiragana characters are not being displayed correctly. This is what it looks like:

![screenshot](https://cloud.githubusercontent.com/assets/5281871/6986438/355ff72a-da0b-11e4-8d7a-c930e3d1b043.png)

I'm testing it by this command:
```
echo "hello おはよう" | lemonbar -g "x12+0+0" -f "-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1","-mplus-gothic-medium-r-normal--10-100-75-75-c-100-jisx0208.1990-0" -u 1 -B "#FF1D1F21" -F "#FFC5C8C6" -p
```

However, if I change the mplus font to -misc-fixed-medium-r-normal-ja-0-0-75-75-c-0-iso10646-1, it works fine
```
echo "hello おはよう" | lemonbar -g "x12+0+0" -f "-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1","-misc-fixed-medium-r-normal-ja-0-0-75-75-c-0-iso10646-1" -u 1 -B "#FF1D1F21" -F "#FFC5C8C6" -p
```
![screenshot](https://cloud.githubusercontent.com/assets/5281871/6986601/b772fa68-da0c-11e4-9352-9b76857454aa.png)

Of course, I do not like this particular font. So is there any way I can get mplus fonts to display correctly on bar? It works fine in the terminal, which I'm using urxvt and set my fonts through .Xresources. Thanks.

**Comment by LemonBoy** [comment]
Can you please give a download link for the mplus font?

**Comment by LemonBoy** [comment]
Quick follow-up, the reason its not working is simple: the font uses the jisx0208.1990 codepage while the text is passed in as ucs-2. Gotta love the ancient technology heh, I don't think this is going to be fixed as that'd mean to include huge-as-fuck [1] translation tables for the various codepages.

[1] http://cvs.schmorp.de/rxvt-unicode/src/table/

**Comment by reportados123** [comment]
I see, thanks for trying and the information though!
