### ISSUE TITLE
unicode issues with double-width characters

### ISSUE THREAD

**Issue by lukasepple** [LemonBoy/bar#117]
## The Problem
I have a bar output that contains some special unicode pictograms. These are all double-width unicode characters.

The bar output send to lemonbar renders fine in terminal emulators that are not broken (mostly libvte-based terminal emulators like termite, gnome-terminal…). It does not render in urxvt, probably st won't work, too.

lemonbar is configured to use GNU Unifont (also see note below)

This is what lemonbar looks like when the script below is run:
![2015-04-11-004855_592x72_scrot](https://cloud.githubusercontent.com/assets/3154475/7098864/8f08dad0-dfe7-11e4-9213-4502fbf1912f.png)

It looks like this if the pipe into lemonbar is removed in termite:
![2015-04-11-011425_453x122_scrot](https://cloud.githubusercontent.com/assets/3154475/7098879/239862f6-dfe8-11e4-8e53-f552bd359be8.png)

I have tested some normal-width unicode characters  which all rendered correctly, so this seems to be a double-width character issue.

## The Script
```bash
#!/bin/bash
BATC=/sys/class/power_supply/BAT0/capacity
BATS=/sys/class/power_supply/BAT0/status

clock() {
    date "+$(unicode_clock.py)  %d.%m.%Y %H:%M:%S"
}

battery() {
    status=$(cat "$BATS")
    cap=$(cat "$BATC")
    test "$status" = "Charging" && echo -n '🔌  ' || echo -n '🔋  '
    echo "${cap:-1}%"
}

volume() {
    loudness=$(amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p')
    speakersymbol=$((amixer get Master | grep '\[on\]' > /dev/null) && echo -n "🔊" || echo -n "🔇")
    echo "$speakersymbol  ${loudness:-1}%"
}

network() {
    status=$(ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n "Up" || echo -n "Down")
    echo "🖧  $status"
}
while true; do
    buf="$(network) | $(volume) | $(battery) | $(clock)"
    echo "$buf"
    sleep 1
done | lemonbar -f '-*-unifont-medium-*-normal-*-16-*-*-*-*-*-*-*'

# vim :set ft=bash:
```

## Note on fonts
GNU Unifont has got all the characters I use, so for reproducing it is probably a good idea to install it like this:
```
cd .local/share/fonts
wget http://unifoundry.com/pub/unifont-7.0.06/font-builds/unifont-7.0.06.ttf
wget http://unifoundry.com/pub/unifont-7.0.06/font-builds/unifont_upper-7.0.06.ttf
fc-cache -fv
```

Unifont has got more characters than the maximal amount of chars in a ttf file so there are two of them. I had issues with missing chars with the official ArchLinux package which also is outdated. I only know that the debian unifont package is behaving correctly.

It would be nice if you could look at this!

**Comment by lukasepple** [comment]
I am using the archlinux `lemonbar-git` package build.

**Comment by LemonBoy** [comment]
This is one of the big pitfalls of using technology from the '80 to render text.
Our dear Xorg is able to represent every glyph of the Basic Multilingual Plane (BMP for short) plus some codepage trickery but sadly the icons you're after are in the unreachable part of the plane. The terminals (eg. the vte-based ones) built with modern technology (eg. pango) don't have such restriction and are deemed cool by everyone.
