### ISSUE TITLE
Cannot parse fonts with spaces in their names in CLI

### ISSUE THREAD

**Issue by johan-bjareholt** [LemonBoy/bar#119]
I want to use the Liberation Mono font, but realized that font names with spaces in them can't get parsed. The reason: because it's simply because argv in main is separated by spaces and nothing handles that x fonts can have spaces in them when they actually should be merged. I'm not sure how i'd code that in a clean way, which is why i am opening this issue.

Examples

Doesn't work:
- -\*-liberation mono-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*
- -\*-dejavu sans mono-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*
- -\*-andale mono-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*

Does work:
- -\*-arial-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*
- -\*-verdana-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*-\*

Using "" around the font name doesn't make any difference either

**Comment by 8carlosf** [comment]
can you show us the command?
I did 
lemonbar -f "-*-dejavu sans mono-*-*-*-*-*-*-*-*-*-*-*-*"
and it worked just okay..
also did
lemonbar -f -*-dejavu\ sans\ mono-*-*-*-*-*-*-*-*-*-*-*-*
it is a little more strange, but works.. (the \[SPACE] is really the char space and not a arg separator)

**Comment by johan-bjareholt** [comment]
Alright, it seems like it was simply me that was tired and stupid, closing.

Both commands worked when typed straight in the cli, but when using the font it a bash variable it didn't so i guess that it's a bash issue rather than a bar issue. Only the first worked when using variables though.

Sorry for taking your time.

**Comment by fbt** [comment]
You probably did not quote the variable.

**Comment by johan-bjareholt** [comment]
Should perhaps explain a little more in detail.
Quoting in the variable in the variable didn't work either.

Wanted to execute it with lemonbar -p -f $FONT, trying:
- FONT="-*-liberation\ mono-medium-r-*-*-12-*-*-*-*-*-*-*"
- FONT="\"-*-liberation mono-medium-r-*-*-12-*-*-*-*-*-*-*\""
- FONT='"-*-liberation mono-medium-r-*-*-12-*-*-*-*-*-*-*"'

None of these worked, but when simply replacing the actual variable with the content of the variable (excluding the outer quotes), it worked.
Since i have 3 monitors and execute 3 bars it looks ugly in my startup script, but i can live with that.

**Comment by 8carlosf** [comment]
the ideal is to use lemonbar -p -f "$FONT" this way you only have to set the variable right, and that you can test using the echo command in your terminal
``` ini
FONT='-*-dejavu sans mono-*-*-*-*-*-*-*-*-*-*-*-*'
lemonbar -f "$FONT"
```
or
``` ini
FONT="-*-dejavu sans mono-*-*-*-*-*-*-*-*-*-*-*-*"
lemonbar -f "$FONT"
```
or even (more ugly)
``` ini
FONT=-*-dejavu\ sans\ mono-*-*-*-*-*-*-*-*-*-*-*-*
lemonbar -f "$FONT"
```
I hope this helped..

**Comment by johan-bjareholt** [comment]
Thanks @8carlosf, that works wonders!
