### ISSUE TITLE
Clickeable bar - not just the text.

### ISSUE THREAD

**Issue by zexa** [LemonBoy/bar#120]
Hello,  
I'm doing some work on my bar and I noticed that %{A:urxvt:}something%{A} only works when you click on the text and there's basically no way to make the whole bar or area click-able.   
Could you please add a feature to make an area or the whole bar click-able?  
Zexodus
  
P.s. A workaround for this is to center text with spaces through out the bar.

**Comment by Mishio595** [comment]
You can achieve this by adding spaces.  %{A:urxvt:}      %{A}  will make an clickable area several spaces wide. My bar uses clickable underlined spaces.

**Comment by zexa** [comment]
Isn't that just an incredibly goofy workaround?

**Comment by Mishio595** [comment]
It simply uses the very literal nature of bar. It also looks really nice

**Comment by onodera-punpun** [comment]
>It simply uses the very literal nature of bar. It also looks really nice

``%{A:urxvt:}                                                                                                                              %{A}``

doesn't look nice at all in my opinion.

+1

**Comment by Mishio595** [comment]
I should have been more clear. Here's an example line from my bar scripts.

    %{U$ACTIVE}%{A:bspc desktop -f $name:}%{+u}   %{A}%{-u}

My bar looks like this
![bar](https://cloud.githubusercontent.com/assets/3598536/8276662/bca52a96-187e-11e5-93b1-76aa2fa2c80b.png)

**Comment by LemonBoy** [comment]
Let's keep #175 only for this.
