### ISSUE TITLE
Can't display unicode characters using \uXXXX

### ISSUE THREAD

**Issue by Jorick** [LemonBoy/bar#121]
Hi,

I'm trying to add a unicode character as a separator for my statusline ( \u276f ) but I can't get it to display.

I've tried the following:
* *using printf and pipe it to the bar (based on the example config for bspwm):*
.....
sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} $(printf "\u276f") ${line#?} %{B-}%{F-}"
.....
printf "%s\n" "%{l}${wm_infos}${title}%{r}${conky}${sys_infos}"

* *Putting printf in my conkyrc:*
.... ${exec printf "\u276f"} ....

Both options work fine when running in urxvt, the font I use supports the character but I just can't get it working for lemonbar, it just prints an empty space.
Am I doing something wrong or is it just not supported ?

**Comment by LemonBoy** [comment]
This happens when none of the fonts you've specified contain that glyph (or some random codepage madness happens)

**Comment by Jorick** [comment]
I'm using profont for both urxvt and the bar, with the same font settings. Since I have no problem displaying the char in urxvt I don't think it's a font problem.

**Comment by LemonBoy** [comment]
No, the font has only 255 glyphs, you can verify that yourself by using xfd. Mistery solved.
