### ISSUE TITLE
What is the difference between dzen2?

### ISSUE THREAD

**Issue by pickfire** [LemonBoy/bar#123]

**Comment by LemonBoy** [comment]
Actively developed, no Xlib/Xft, no Xbm, lets you align the text. And made with love.

**Comment by pickfire** [comment]
What about icons? And drop-down menu?

**Comment by onodera-punpun** [comment]
>What about icons?
See no xbm, lemonboy is working on it I think though: https://github.com/LemonBoy/bar/issues/79

>And drop-down menu
nope
