### ISSUE TITLE
Add config.h

### ISSUE THREAD

**Issue by MehLON** [LemonBoy/bar#125]
I would like to set the `-d` option as a default, but there's no config.h to do this in, could this be added?

**Comment by LemonBoy** [comment]
Well, the config.h is no more used as everything can be set at run-time, isn't that enough for you ?

**Comment by MehLON** [comment]
Well, I would just prefer to set it at compile time, but if you don't think that's necessary that's fine too.

**Comment by LemonBoy** [comment]
Well if you really want to set it at compile time feel free to do so, you just have to modify this [1] line.

[1] https://github.com/LemonBoy/bar/blob/master/lemonbar.c#L92

**Comment by MehLON** [comment]
Okay, thanks.
