### ISSUE TITLE
[Feature request] Select monitor based on output name

### ISSUE THREAD

**Issue by Slabity** [LemonBoy/bar#126]
For my laptop I commonly connect and disconnect monitors. I'd like to be able to control which monitor Bar goes to by the name of the xrandr output (eDP1, HDMI1, DVI-1, etc) instead of trying to guess which one is the 'nth' monitor using something like `%{Soutput}`, where output can be an xrandr output.

**Comment by jvvv** [comment]
This is should be feasible.
@LemonBoy Are you interested in this? I might have some time in the next three days to hack something for this together. Then you could decide if the code bloat is reasonable or not.

**Comment by LemonBoy** [comment]
Well it's definitely nice to have if XrandR doesn't guarantee a stable order, let's see if the parser can be further stretched heh

**Comment by jvvv** [comment]
I should have something worth testing by the end of the weekend.

**Comment by jvvv** [comment]
Well, lucky for me, it's a long weekend here. Otherwise, I would have had to say I missed my deadline ;) I have an initial port of the feature. It seems to do what was requested, but could use a bit more testing.  See the pull request at https://github.com/LemonBoy/bar/pull/127 for more detail.

**Comment by LemonBoy** [comment]
Implemented by #127 (better late than never, no?)
