### ISSUE TITLE
Click area not working

### ISSUE THREAD

**Issue by NicolasCARPi** [LemonBoy/bar#129]
Hello,

First I want to thank you for providing us this free piece of software :)

I want to use the clickable area feature, but I cannot manage to make it work, all it does is print the command in STDOUT, but not execute it.

The command is `amixer set 'Master' 50%`.

The code to test it out is : 
`echo "%{A:amixer set 'Master' 50%:}CLICK HERE%{A}" | lemonbar -b -p`

When the zone is clicked, the command is output to stdout, but I want to execute it of course. What am I doing wrong ? :)

The full setup is with bspwm.

Regards,
~Nico

**Comment by otommod** [comment]
```echo "%{A:amixer set 'Master' 50%:}CLICK HERE%{A}" | lemonbar -b -p | sh``` works. Of course, you should quote the "command" properly. And that means quoting two times, one for echo, one for the eventual execution in sh. In your case, nothing needs to be done, but keep that in mine if you are using more complex commands.

**Comment by NicolasCARPi** [comment]
Thanks, it's working now :)

Cheers \o/
