### ISSUE TITLE
xcb/xinerama.h: no such file or directory

### ISSUE THREAD

**Issue by Talor-A** [LemonBoy/bar#130]
After cloning lemonbar and running make, I get this error. libxinerama1 and libxinerama-dev are both installed and up to date. I'm on ubuntu 14.04 with herbstluftwm. Am I installing this wrong? I'm not too familiar with compiling programs for ubuntu, and I just tried download zip -> unzip -> cd -> make. is there anything I'm missing? thanks.

**Comment by otommod** [comment]
Searching through the debian packages, I think ```libxcb-xinerama0``` is what you want. It did say ```xcb/xinerama.h``` after all.

**Comment by Talor-A** [comment]
@otommod yes that fixed it. Thanks.

**Comment by Power-Inside** [comment]
I think it's `libxcb-xinerama0-dev` @otommod. Installing just the `libxcb-xinerama0` did not fix my issue

**Comment by niedzielski** [comment]
@Power-Inside libxcb-xinerama0-dev works for me!

**Comment by DerMeulendreeZ** [comment]
I needed to add libxinerama-dev.
