### ISSUE TITLE
Support for mousewheel

### ISSUE THREAD

**Issue by rr-** [LemonBoy/bar#131]
In i3 we can switch workspaces by scrolling the mouse wheel when hovering any place inside the i3-bar. It would be nice if lemonbar provided users with ability to run arbitrary commands when mouse wheel event is intercepted.

I guess this is very similar to #120.

**Comment by Bfgeshka** [comment]
Wheel already works as A4 and A5 mouse buttons.

**Comment by rr-** [comment]
You're right, I missed it. Sorry.
