### ISSUE TITLE
Detect screen change

### ISSUE THREAD

**Issue by woho** [LemonBoy/bar#135]
It would be great it bar detected screen property changes, e. g. a resolution change, using xcb_randr_notify[...].
Currently, when the resolution is changed, the text positions in the bar are not recalculated properly.

**Comment by ke7ofi** [comment]
I feel like that could/should be done with an external script.

**Comment by LemonBoy** [comment]
Feel free to send a PR, I don't have any idea of how much code it'd take right now, but I'd say the 'Use a script, Luke' advice is the best option.

**Comment by andyph666** [comment]
woho: Did you manage to figure it out by any chance? Just tweaked a config but am not sure how to get lemonbar to calculate the text positions on a resolution change. (using vmware at the moment so it would be quite useful to do that)

**Comment by woho** [comment]
andyph666: No, I have not tried it yet.

**Comment by DelusionalLogic** [comment]
I've tried doing some small tests to see if it's possible to solve this. Currently i have a very hacky solution that requires 44 new lines. Most of those are duplication, but i suspect the amount of code will grow as i form this into an actual patch.

It requires:
 - Getting all the monitors from randr
 - Re-sizing the windows
 - Creating new pixmaps
 - Re rendering the bar

It seems like a fairly simple change. Thoughts? Is 100 lines too much for this feature?
