### ISSUE TITLE
[Feature Request] Ability to change bar's WM_NAME with a launch option.

### ISSUE THREAD

**Issue by dylanaraps** [LemonBoy/bar#136]
I'd love this as I have 3 bars running and I'd like each bar to have a different name for Compton's shadow excludes.

**Comment by motdef** [comment]
Seconding this for the same reason, would like control over which bars have shadows drawn on them

**Comment by ifiwonder** [comment]
wrote a patch for it probably not up to snuff but it works 

    1074c1074
    < init (char * wm_name,bool wm_change)
    ---
    > init (void)
    1143,1145d1142
    <     if(wm_change == true){
    <         xcb_change_property(c, XCB_PROP_MODE_REPLACE, monhead->window, XCB_ATOM_WM_NAME, XCB_ATOM_STRING, 8 ,strlen(wm_name), wm_name);
    <     }
    1220,1221d1216
    <     char * wm_name = NULL;
    <     bool wm_change = false;
    1237c1232
    <     while ((ch = getopt(argc, argv, "hg:bdf:a:pu:B:F:n:")) != -1) {
    ---
    >     while ((ch = getopt(argc, argv, "hg:bdf:a:pu:B:F:")) != -1) {
    1241c1236
    <                 printf ("usage: %s [-h | -g | -b | -d | -f | -a | -p | -u | -B | -F | -n]\n"
    ---
    >                 printf ("usage: %s [-h | -g | -b | -d | -f | -a | -p | -u | -B | -F]\n"
    1250,1251c1245
    <                         "\t-F Set foreground color in #AARRGGBB\n"
    <                         "\t-n Set WM_NAME\n", argv[0]);
    ---
    >                         "\t-F Set foreground color in #AARRGGBB\n", argv[0]);
    1261d1254
    <             case 'n': wm_name = optarg; wm_change = true;  break;
    1272c1265
    <     init(wm_name,wm_change);
    ---
    >     init();

**Comment by LemonBoy** [comment]
Done.
