### ISSUE TITLE
Bar won't change width

### ISSUE THREAD

**Issue by SliinQ** [LemonBoy/bar#138]
I am trying to change the width of the bar but it just doesn't seem to work. I have no idea what I am doing wrong. I am using this command:
`echo "%{l}Left %{c}Center %{r}Right" |lemonbar -B blue -g 1500x20+100+20 -p`
![issue](http://i.imgur.com/11ZnoH8.png)

As you can see the text does adapt to the new size although the bar itself does not.

**Comment by otommod** [comment]
Maybe it's your window manager's fault? Try running `lemonbar` with the `-d`. For me this solves these kind of problems in awesome WM.

**Comment by SliinQ** [comment]
Oh you are right! I am currently using i3-gaps and with -d it does indeed work just fine. 
Thanks!
