### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by DelusionalLogic** [LemonBoy/bar#140]
The documentation on the formatting blocks are unclear . It's not specified whether you are allowed to have multiple options within a single block.

The current implementation means that you are indeed allowed to have multiple options within a single formatting block, but that has implications for the font selection option, which is implemented incorrectly seen from the documentation.

The font selection option reads
>Any other value (for example -) resets the bar to normal behavior (matching the first font that can be used for that character).

This doesn't specify how many characters are to be included in the font selection index. It's therefore impossible to know when the next option will be parsed from. This has lead to the wrong implementation of the font selection [here](https://github.com/LemonBoy/bar/blob/a9f285fd2866ab3451b8dd7468853c141691024f/lemonbar.c#L543-L549)

The problem is that it will only read a number, with all indices outside of the font list being automatic font selection. This is not in accordance with the documentation which explicitly specifies `-` as a valid reset character, and says anything not a 1 indexed font number would be treated as a reset, including random strings.

There are several ways to fix this, the easiest being to change the documentation to make it clear that `T` only accepts numbers, and that you can have multiple options following each other. This has the disadvantage of making `T` different from `F` and `B` which both support `-` as the reset.

If `T` should be canonical with `F` and `B`, `-` should be explicitly allowed, which requires a trivial change to the code and the documentation.

I would gladly make the changes, but I'd like the hear the arguments of the maintainer(s) first.

**Comment by LemonBoy** [comment]
Go for it, I'm not a native English speaker and writing the documentation turned out to be an hard task.
And yes, the T should behave like F and B with respect to the hyphen handling
