### ISSUE TITLE
Could not allocate the color "black"

### ISSUE THREAD

**Issue by nekrilia** [LemonBoy/bar#143]
Trying to troubleshoot my installation and I am getting this when running lemonbar from terminal:
```
Could not allocate the color "black"
Could not allocate the color "white"
```
running panel from terminal yields:
```
Could not allocate the color "black"
Could not allocate the color "white"
Could not load font ""
```

**Comment by LemonBoy** [comment]
I've heard that orange is the new black.
Can you please give more informations such as your OS (and version) ?

**Comment by nekrilia** [comment]
My wife mentioned something along those lines.
And yes!
4.1.3-1-ARCH
lemonbar version a390ef6

**Comment by LemonBoy** [comment]
This is weird, to be honest I've never managed to replicate this damn problem.
How are you invoking lemonbar ?

**Comment by nekrilia** [comment]
Since invoking it in ~/.config/bspwm/bspwmrc didn't show anything, I tried seeing what error messages I would get if I invoked panel and lemonbar from my terminal.

**Comment by infernix** [comment]
I ran into this on Debian Sid and bisected it to this:

4d5f9b60e30b8ffa117b71cc9115152464373e32 is the first bad commit
commit 4d5f9b60e30b8ffa117b71cc9115152464373e32
Author: LemonBoy <thatlemon@gmail.com>
Date:   Mon Feb 24 12:35:56 2014 +0000
<pre>

    Use 32bit visuals when available

:100644 100644 6f3be149894e60502c7332290f3d77a8b8951167 412e0bde088922d03ff78e391c8cf5ed163117ab M	README.pod
:100644 100644 636a94637d5b608c0e343bc416c2b3eac990280f 5d17968db4b5ffcc5b33668c1ec184e4b57c6fc8 M	bar.c
</pre>

So looks like it's related to alpha? Any ideas what to look at?

**Comment by jvvv** [comment]
The error message about color allocation failure here is not related to rgba. It's outside the 'Hex representation' block and happens at the named color allocation. I suspect the trouble has something to do with the colormap. I tried changing the alloc parameter of the xcb_create_colormap call in xconn(); from XCB_COLORMAP_ALLOC_NONE to XCB_COLORMAP_ALLOC_ALL. After that change, I see the same error. This feels like a heisenbug. Tracking it down could be interestingly frustrating.

**Comment by LemonBoy** [comment]
Named colors aren't parsed anymore, hence this should be fixed. Please re-open it if it's not.
