### ISSUE TITLE
Autohide mode

### ISSUE THREAD

**Issue by mox-mox** [LemonBoy/bar#145]
Hey,

I really like lemon bar, thanks for the work!
However, is there a way to have lemonbar autohide like i3bar with "mode hide"?
Or, put differently, would it be much work, to implement this?

Regards,
mox

**Comment by LemonBoy** [comment]
I think that could be easily scripted using external tools

**Comment by QiangF** [comment]
@LemonBoy Can you provide an example?
i3bar only shows when windows key is pressed down.
