### ISSUE TITLE
Mismatching ordering of monitors in accordance to bspwm

### ISSUE THREAD

**Issue by Ploppz** [LemonBoy/bar#148]
I didn't know whether I should make this entry in `bspwm` or `bar`. But it seems like `bspwm` has some ordering defined already: My issue is when calling `bspc control --subscribe`. Initially, and when anything changes, it writes out monitor and desktop info. The monitors seem to be sorted by how they appear, from left to right, in the layout, but I haven't tested with placing the monitors on top of each other yet.

I have used the output of this command as a basis to keep track of which monitor is in focus in order to change the color of the corresponding part of bar shown on each monitor, and to write monitor-specific information.

So using the ordering of this command, I created arrays in my panel script whose indices are where a monitor appears in the output of `bspc control --subscribe` (first, second..), and whose values are whether the monitor is focused and (separate array) info about the desktop of this monitor.

This is kind of what is output in the end. 
`echo "%{S0}blabla .. ${monitorInfo[0]} .... %{S1} .... ${monitorInfo[1]}"`
It worked until I changed the layout of my monitors, but I now want a general configuration that updates correctly whenever I plug in any monitor. I'm dependent that bar's ordering of monitors matches that of bspwm, and I'm not sure which program I should ask to change.

**Comment by LemonBoy** [comment]
The monitors are already sorted by coordinate and I don't think there's a better way to sort them.

**Comment by Ploppz** [comment]
You are right; I tried again and bar has a defined ordering, while bspwm does not. I'll go ask there.
