### ISSUE TITLE
Cannot load any font

### ISSUE THREAD

**Issue by tudurom** [LemonBoy/bar#149]
When I want to specify a font I want to use with lemonbar, it fails with the message `Could not load font`. I tried with "DejaVu Sans", "FontAwesome" and "Source Sans Pro". Neither work. All of them are installed. Running Arch Linux

**Comment by Bfgeshka** [comment]
Original version of lemonbar ain't using XFT, so you cannot use TTF fonts.

**Comment by tudurom** [comment]
So, what type of fonts can I use? Or, is there a fork available?

**Comment by Bfgeshka** [comment]
You can use bitmap fonts here. And yes, fork exists.

**Comment by tudurom** [comment]
Thanks.
