### ISSUE TITLE
Fonts cause segmentation fault

### ISSUE THREAD

**Issue by Vintodrimmer** [LemonBoy/bar#152]
I've updated the bar and now I can't use terminus, which is a bummer, since the default font doesn't support cyrillic.

For example
`lemonbar  -g 1480x15+540 -f "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*" -B "#FF4B4948" -F "#FFDEDBD6"` 
now results in
` zsh: segmentation fault  lemonbar -g 1480x15+540 -f "-*-terminus-*-*-*-*-12-*-*-*-*-*-*-*" -B  -F`

Previous version worked like a charm.

**Comment by LemonBoy** [comment]
Fixed.
