### ISSUE TITLE
Usage of ${S}

### ISSUE THREAD

**Issue by Tmplt** [LemonBoy/bar#156]
Pardon me for creating an issue that can be solved by reading the documentation. It's just that I don't understand it completely.

I want to only render the bar on my second monitor, but I'm unsure how to pass the `${S}`. Could an example be added?

Thanks in advance.

**Comment by benjaminwhite** [comment]
I have to agree with you. You probably shouldn't create an issue for this. Especially because your problem is a simple syntactic mistake: use `%` not `$`.

Also, Github is a wonderful source for examples of lemonbar being used (and most configuration files).
