### ISSUE TITLE
Persistent hidden clickable areas

### ISSUE THREAD

**Issue by alexozer** [LemonBoy/bar#160]
Consider the following script, lemontest.sh;

```bash
#!/bin/bash

echo '%{A:area0:}Area 0    %{A}%{A:area1:}Area 1%{A}'
echo '%{A:area0:}Area 0    %{A}'

sleep 100
```

And its execution: `./lemontest.sh | lemonbar`

lemonbar shows the text "Area 0" and outputs "area0" to stdout when clicked, but when the empty region to the right of "Area 0" is clicked, lemonbar outputs "area1" even though this clickable area has been removed.

I've found other more complex inputs which remove clickable areas in a similar way, and some of these cause lemonbar to output even stranger things, such as newlines and '}' symbols. I could try to provide these if necessary.

**Comment by LemonBoy** [comment]
I managed to reproduce the issue and fix it, please let me know if that's enough :)

**Comment by alexozer** [comment]
Seems fixed, thanks!
