### ISSUE TITLE
[Feature request] Default underline color

### ISSUE THREAD

**Issue by tudurom** [LemonBoy/bar#161]
I would like to specify bar's default underline color as a parameter, something like:

```
lemonbar -g "widthxheight+x+y" -f ...skip... -U #65737e
```

Any interest?

**Comment by JeromeBon** [comment]
@LemonBoy Are you interested in this? If it's the case I can prepare a PR.

**Comment by LemonBoy** [comment]
Sure thing, let's do this for consistency sake.
