### ISSUE TITLE
Background color breaking when loop piped into lemonbar

### ISSUE THREAD

**Issue by Marcel-Robitaille** [LemonBoy/bar#167]
I have a setup where I am piping the time into lemonbar on a loop. Essentially I have three sections of the bar with two different background colours. Everything works fine until the time gets piped in on the right hand side. At that point the background colour of the time over wrights the background colour I had set. Here are some screenshots to help explain what I am talking about.

This is what I want:
![GOOD](http://i.imgur.com/7VrRtHW.png)

This is what I get:
![BAD!!](http://i.imgur.com/m4xPHMT.png)

Config files: https://github.com/Marcel-Robitaille/dotfiles

Edit: I am using the kernel 4.3.3-3-Arch with i3 and compton.

**Comment by krypt-n** [comment]
Looks like you are using the xft-Version. Can you reproduce your problem with the standard version from this repo?

**Comment by Marcel-Robitaille** [comment]
Yes it is also happening in the standard version. I was able to fix it by adding "%{B-}" at the end of the line.
