### ISSUE TITLE
Ugly looking font

### ISSUE THREAD

**Issue by arkrost** [LemonBoy/bar#173]
Hi!

I'm trying to use the following font `FONT='-*-hack-*-r-*-*-12-*-*-*-*-*-*-*'`. It looks good in apps with xft support and in bar with xft patch applied. But if I set it directly this way, then it looks weird. Bitmap fonts (like terminus) in the oter hand look good.

![lemonbar](https://cloud.githubusercontent.com/assets/1239844/13367239/16127efc-dcf2-11e5-8176-5a526d65cf91.png)

Please suggest what can I deal with it.

**Comment by LemonBoy** [comment]
Love it or leave it, just because it has a xfld descriptor it doesn't mean it'll be good looking w/O the Xft rendering
