### ISSUE TITLE
Set WM_CLASS

### ISSUE THREAD

**Issue by CrackedP0t** [LemonBoy/bar#174]
It would be very useful to set the WM_CLASS property of the Lemonbar windows to something like "Lemonbar", and/or to add a flag like "-n" to set it on the command line.

My specific use case is targeting it with BSPWM rules, but I'm sure there are many other uses as well.

**Comment by dylanaraps** [comment]
I might be wrong but can't you use `WM_NAME` with BSPWM rules? I'm pretty sure 
you could get it working this way. Just name each bar something unique with `-n`.

**Comment by Wildefyr** [comment]
WM_CLASS would be still be useful, especially as it would follow X11 conventions. I can already see uses for this with wmutils for example.

**Comment by LemonBoy** [comment]
The customizable `WM_NAME` allows people to have custom rules for each bar, `WM_CLASS` should be set to a constant string, removing the ability to do so.
Closing this for now, if you have some more question feel free to re-open it.

**Comment by Iambecomeroot** [comment]
@dylanaraps How do you do that? I tried that with `bspc rule -a notification state=floating` but my bar with `-n "notification"` doesn't float. I have verified the `WM_NAME` and the state with `xprop`. Is there a special syntax for name rules as apposed to class rules?

**Comment by dylanaraps** [comment]
It's been well over a year since I've used BSPWM, I wouldn't have a clue anymore. I've moved on to using `dunst` and `notify-send` for my notification needs.

**Comment by Iambecomeroot** [comment]
What de/wm do you use now? I tried the dunst thing for a while. It was nice but how do you handle click events?

**Comment by Iambecomeroot** [comment]
I'm not familiar with bspwm's source but [here](https://github.com/sunaku/bspwm/blob/3d95e7e6d2611f20b4fb19a7e1a46884d75e37be/rules.c#L15), assuming `r->cause.name` is the name in the config and `reply.instance_name` is the `WM_NAME`, it looks like is should work.
