### ISSUE TITLE
Too many clickable areas bug out the panel

### ISSUE THREAD

**Issue by fbt** [LemonBoy/bar#177]
All is well: https://8fw.me/hell/e69ceb6a3b3a739d885eed1f9e6b0f8717dfd459.png

But add another area and bam: https://8fw.me/hell/8b1401a957005d4a263e22a82ac5c5b2083c4eb2.png

I'm using HEAD.
The script is my own [frozenbar](https://git.fleshless.org/frozenbar/about/), specifically the one causing it is the [taskbar module](https://git.fleshless.org/frozenbar/tree/mod/bspwm_taskbar). If I remove the clickable areas from the titles, it works as intended:

https://8fw.me/hell/e74a6ba10cbb5ba5201dcf2aafcf1ec286dba3dc.png

**Comment by fbt** [comment]
I should add that this was not the case in 1.1

**Comment by neeasade** [comment]
there is a flag to set the number of clickable areas `-a`, which defaults to 10

**Comment by fbt** [comment]
Yeah, I've encountered that commit while trying to figure out which one introduced the behaviour. So nvm, it's just me being stupid.
