### ISSUE TITLE
Not loading second font

### ISSUE THREAD

**Issue by kevinvdburgt** [LemonBoy/bar#179]
Hello,

I've an issue when loading the second font (for icons) into lemonbar. When using this script:
```
echo "Hello World ( clock icon: Õ, volume icon: Ô)" | lemonbar \
  -p \
  -f "-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1" \
  -f "-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1" \
  -g "x14" \
  -B "#FF1D1F21" \
  -F "#FFC5C8C6"
```
It loads the text font correctly but doesnt load the icon font.
![2016-04-22-223833_279x19_scrot](https://cloud.githubusercontent.com/assets/1987802/14751453/37a57318-08ca-11e6-805d-ab2c66390fdc.png)

When running the following script (swapped the -f fonts) it doesnt load my text font but it displays the icon font.
```
echo "Hello World ( clock icon: Õ, volume icon: Ô)" | lemonbar \
  -p \
  -f "-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1" \
  -f "-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1" \
  -g "x14" \
  -B "#FF1D1F21" \
  -F "#FFC5C8C6"
```
![2016-04-22-223820_458x24_scrot](https://cloud.githubusercontent.com/assets/1987802/14751461/45ed608e-08ca-11e6-9632-aaa60ad10add.png)

**Comment by neeasade** [comment]
in your first script, try changing your input like:

echo "Hello World ( clock icon: %{T2}Õ%{T-}, volume icon: %{T2}Ô%{T-})"


On Fri, Apr 22, 2016 at 1:39 PM, Kevin vd Burgt <notifications@github.com>
wrote:

> Hello,
>
> I've an issue when loading the second font (for icons) into lemonbar. When
> using this script:
>
> echo "Hello World ( clock icon: Õ, volume icon: Ô)" | lemonbar \
>   -p \
>   -f "-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1" \
>   -f "-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1" \
>   -g "x14" \
>   -B "#FF1D1F21" \
>   -F "#FFC5C8C6"
>
> It loads the text font correctly but doesnt load the icon font.
> [image: 2016-04-22-223833_279x19_scrot]
> <https://cloud.githubusercontent.com/assets/1987802/14751453/37a57318-08ca-11e6-805d-ab2c66390fdc.png>
>
> When running the following script (swapped the -f fonts) it doesnt load my
> text font but it displays the icon font.
>
> echo "Hello World ( clock icon: Õ, volume icon: Ô)" | lemonbar \
>   -p \
>   -f "-xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1" \
>   -f "-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1" \
>   -g "x14" \
>   -B "#FF1D1F21" \
>   -F "#FFC5C8C6"
>
> [image: 2016-04-22-223820_458x24_scrot]
> <https://cloud.githubusercontent.com/assets/1987802/14751461/45ed608e-08ca-11e6-9632-aaa60ad10add.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/LemonBoy/bar/issues/179>
>



-- 
Nathan Isom
Computer Science
Kansas State University

**Comment by kevinvdburgt** [comment]
@neeasade  Thanks, this fixed my issue :+1:
