### ISSUE TITLE
-n argument for panel name garbles text

### ISSUE THREAD

**Issue by rohshall** [LemonBoy/bar#184]
When I invoke lemonbar with -n bspwm_panel, it periodically garbles text. However, if I remove this argument, it works. The relevant diff in my bspwm config is:
`
-panel_bar | lemonbar -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

+panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &
`
I am using the latest version in the git repository.  I have just a few programs writing to the FIFO.
`
bspc subscribe report > "$PANEL_FIFO" &                                                                                                           

xtitle -sf 'T%s' > "$PANEL_FIFO" &                                                                                                                

/usr/local/bin/clock -sf 'S%a %m/%d %H:%M' > "$PANEL_FIFO" &                                                                                      

battery -n1 -sf"B%i" > "$PANEL_FIFO" &                                                                                                            `

**Comment by LemonBoy** [comment]
Sigh, the latest commit should fix the problem

**Comment by otommod** [comment]
A slightly irrelevant question:
  * [here](https://github.com/LemonBoy/bar/blob/master/lemonbar.c#L1211) `monhead` is used
  * [here](https://github.com/LemonBoy/bar/blob/master/lemonbar.c#L767) `mon` is used

Can these both be correct?  I don't have a multihead setup (in fact, I'm not even using lemonbar right now), so I can't actually test.

**Comment by LemonBoy** [comment]
It's a bug indeed, thanks for reporting it :)

**Comment by rohshall** [comment]
Actually, it's not working correctly for me, even if I remove the "-n" argument. My understanding is programs that write to FIFO don't have to write all values in every line. So, my battery or clock scripts can just write their own values at appropriate positions keeping the other values blank and lemonbar will aggregate these values while drawing the bar. If this is the case, the text is getting garbled now.

**Comment by LemonBoy** [comment]
Well, the `-n` option shouldn't affect how text is parsed at all...
