### ISSUE TITLE
parsing uri's in clickable area

### ISSUE THREAD

**Issue by cellsheet** [LemonBoy/bar#191]
so when I tried to make a clickable area for a url on xdg-open, I got `file 'https' does not exist` only to find out the command being returned was `xdg-open https`, truncating the actual url. Lemonbar seems to be parsing the ending `:` in `%A{:command:}`. I would modify the string to work, but xdg-open can only work with the http(s) uri preceding the actual link, as my error would then be `xdg-open: file 'www.example.com' does not exist`.

**Comment by LemonBoy** [comment]
`%{A:echo http\://goog.le:}You have to escape the :%{A}`
