### ISSUE TITLE
bspwm Monitor Resizing

### ISSUE THREAD

**Issue by nckslvrmn** [LemonBoy/bar#194]
Hello,

When running the latest lemonbar in the latest bspwm with no parameters, the bspwm monitor gets modified padding values for the root of the monitor. This happens regardless of which flags you pass (including geometry). I am running arch linux in a vmware fusion and can supply the output of anything needed. Is this a known bug?

**Comment by LemonBoy** [comment]
I'm not sure I understand what the problem, it _might_ be a problem with bspwm and/or VMware.

**Comment by Gingerbreadz** [comment]
I've been running into the same issue after upgrading bspwm from 0.9.1 to 0.9.2 on my laptop, so it might be bspwm related.

![output](https://cloud.githubusercontent.com/assets/4756726/22975402/f06ec3f2-f386-11e6-8869-f49015eaf72b.gif)

**Comment by neeasade** [comment]
> When lemonbar starts, the bottom padding changes, and has to be manually reset.

I believe was amended shortly after the 0.9.2 bspwm release 
commits https://github.com/baskerville/bspwm/commit/201f6e69247af745c2cb6f18f48078973eb64ec9 and  https://github.com/baskerville/bspwm/commit/060f6aec19d146832dd27812fa10a0b63d48f971

**Comment by Gingerbreadz** [comment]
> I believe was amended shortly after the 0.9.2 bspwm release
Indeed, I wasn't able to reproduce my previous issue with a more recent bspwm build (past those 2 commits). Thanks !

**Comment by LemonBoy** [comment]
Closing this then! 🎉
