### ISSUE TITLE
Bar height is taken from monitor even if the bar isn't on it

### ISSUE THREAD

**Issue by fredlebel** [LemonBoy/bar#201]
My setup has three monitors, with two bars (top, bottom) placed on the second (middle) screen using the geometry flag.

In bspwm, if I open a single window on each screen, taking the entire available space, I get this behaviour.

Screen 1: Window reaches top of screen but an empty gap the height of lemonbar is present at the bottom.
Screen 2: Window is properly filling the available space between the two bars.
Screen 3: Window is properly filling the entire screen.

There seems to be something wrong with the bottom bar affecting the first monitor.  I even tried setting the geometry smaller that the middle screen to make sure it wasn't an off-by-one mistake where the bar was barely on the first screen.

This could be an issue with bspwm, not quite sure where the problem is.

**Comment by LemonBoy** [comment]
It may be a problem with how bspwm handles the uneven layout, the `STRUT` values should be correctly set on bar's side.

**Comment by fredlebel** [comment]
Yup, looking a lot more like a bspwm issue.  It doesn't update the layout after removing the bar.  Thanks for the feedback.
