### ISSUE TITLE
Feature request: allow underline/overline to work across alignment 

### ISSUE THREAD

**Issue by neeasade** [LemonBoy/bar#203]
eg `%{l}left %{+uU#ffffffff} %{c} %{-u} center %{r} right` would show `#ffffffff` underline across the left half inbetween 'left' and 'center'.

**Comment by neeasade** [comment]
Maybe the existing draw_shift() method could be used for this on alignment flag?

/cc @Stebalien

**Comment by Stebalien** [comment]
I agree this should work but I don't really have the time to look into this too much at the moment.
