### ISSUE TITLE
Support UTF-8 chars

### ISSUE THREAD

**Issue by vit1251** [LemonBoy/bar#205]
I try to write UTF-8 chars and have no output. Could you explain what problem with?

**Comment by onodera-punpun** [comment]
Either your locale is messed up, or your font doesn't support these characters, try setting a fallback font.

**Comment by vit1251** [comment]
Hello,

    Yep, you was right.

    Problem resolve when I make C MACROS with replace "fixed" on DEFAULT_FONT_NAME and specify totally ISO 10646/Unicode font name.

Thanks.
