### ISSUE TITLE
hover

### ISSUE THREAD

**Issue by Popkultur** [LemonBoy/bar#208]
Hi,

would be nice to be able to do some cursor hover color effect.

**Comment by fheee** [comment]
What do you mean? like when you hover the mouse over the bar, change the color?

**Comment by Popkultur** [comment]
yes, and after clicking on a clickable area, indicating with another color that it has been clicked or that a process is running, so the start of an application can be signaled.

**Comment by fheee** [comment]
The 'indicating with another color' part could be done with the %{Bcolor} and %{Fcolor} 'tags'. i'm going to try adding a "%{H:command} tag, for on hover or something.
