### ISSUE TITLE
lemonbar not displayed with nohup

### ISSUE THREAD

**Issue by kenogo** [LemonBoy/bar#209]
So l just switched from Gentoo to Debian. lemonbar worked without issues on Gentoo, but for some reason, it does not display when I use nohup in Debian. I don't have any idea what the reason for this is and can not find anyone with the same problem online. The problem applies to the official Debian lemonbar release package, but also when I compile the latest release or the upstream code.

This makes lemonbar completely unusable in the context of, say, putting it into i3's config file. To give a specific example: When I create a file `test_lemonbar` with the contents
```
#!/bin/bash
lemonbar -B "#FFFFFF" -g "x20"
```
and execute it from a terminal with `./test_lemonbar`, it runs completely fine. When I execute it using `nohup ./test_lemonbar` though, or when I start it from i3's config file, it just doesn't display anything. `ps -aux | grep lemonbar` reveals that no lemonbar process is running. I also tried adding the `-p` option to `test_lemonbar`, but it didn't change anything.

**Comment by LemonBoy** [comment]
You still have to pipe something into its stdin, eg:
`cat /dev/urandom | nohup ./test_lemobar`
or (if `-p` is added)
`echo "Hello" | nohup ./test_lemonbar`.

If you execute `nohup ./lemonbar` you'll notice a warning such as:
> nohup: ignoring input and appending output to 'nohup.out'
