### ISSUE TITLE
Documentation incomplete: stdin is never mentioned

### ISSUE THREAD

**Issue by danr** [LemonBoy/bar#212]
The documentation in README.md and in the manpage does not explain that the contents of the bar is populated via stdin. 

Examples are also missing. Simple example to get one going like these would be helpful:
```sh
while true; do date; done | lemonbar
```

```sh
cat /etc/hostname | lemonbar -p
```

**Comment by LemonBoy** [comment]
I guess the `README.pod` could use some love, feel free to add a `INPUT` section with a few words about picking the input from stdin and send a PR :)

**Comment by aeosynth** [comment]
an example of font format would be nice as well, since the xft format can't be used
