### ISSUE TITLE
Bg from right part fills the gap between the three sections

### ISSUE THREAD

**Issue by Ploppz** [LemonBoy/bar#213]
Is this behaviour expected?
Here is the data I send to the bar. Pay attention to the end `%{r} 00:31:46`.

```
%{l}%{F#FFF} %{B#111111}  4.119/16 GB RAM %{F#000} %{B#1F4B17}⮀⮁%{F#FFF}  Hello! %{F#1F4B17} %{B#111111}⮀⮁%{F#FFF}   %{F#111111} %{B#00000000}⮀⮁%{F#FFF} %{c}%{F#111111} %{B#00000000} ⮃⮂%{F#FFF}%{B#111} %{F#644}17 %{F#644}2 %{F#644}3 %{F#644}14 %{F#FFF}20 %{F#644}18 %{F#644}4 %{F#644}11 %{F#644}10 %{F#111111} %{B#00000000}⮀⮁%{F#FFF} %{r} 00:31:46
```
Result: https://i.imgur.com/sstD0Se.png

But when I want to specify a background on the right part by changing it to `%{r}%{B#497933} 00:31:46`: https://i.imgur.com/9gXb6XQ.png (please ignore slightly different time of day...)
That is, the background of the right part now fills all the gaps between the left, middle and right sections, as if it leaks.

**Comment by LemonBoy** [comment]
I cannot reproduce this problem, changing the last part to `%{r}%{B#497933} 00:31:46` colours the clock section only.

**Comment by Ploppz** [comment]
Alright; maybe it has to do with what was sent through the pipe just before:

```
#!/bin/bash

L=("%{l}%{F#FFF} %{B#111111}  2.641/16 GB RAM %{F#000} %{B#1F4B17}⮀⮁%{F#FFF}  ⭦ 1.2% %{F#1F4B17} %{B#111111}⮀⮁%{F#FFF}  ⮞ 34 %{F#111111} %{B#497933}⮀⮁%{F#FFF}   %{F#497933} %{B#00000000}⮀⮁%{F#FFF} %{c}%{r}%{B#497933} 18:32:09"\
    "%{l}%{F#FFF} %{B#111111}  2.641/16 GB RAM %{F#00000000} %{B#1F4B17}⮀⮁%{F#FFF}  ⭦ 1.2% %{F#1F4B17} %{B#111111}⮀⮁%{F#FFF}  ⮞ 34 %{F#111111} %{B#497933}⮀⮁%{F#FFF}   %{F#497933} %{B#00000000}⮀⮁%{F#FFF} %{c}%{F#FAC}tiled %{F#111111} %{B#00000000} ⮃⮂%{F#FFF}%{B#111} %{B#111} %{F#554}σ %{B#111} %{F#554}γ %{B#111} %{F#554}δ %{F#FFF}|%{B#111} %{F#554}ο %{B#111} %{F#554}φ %{B#111} %{F#554}τ %{F#FFF}|%{B#111} %{F#9a1}Ε %{B#9a1} %{F#000}Μ %{B#111} %{B#111} %{F#554}λ  %{F#111111} %{B#00000000}⮀⮁%{F#FFF}  %{F#FAC}tile%{r}%{B#497933} 18:32:09")

for text in "${L[@]}"; do
    echo $text
    sleep 1
done
sleep 999999
```

Try to pipe this to `lemonbar`. The second item in `L` should be just about the same as that in the original post.
