### ISSUE TITLE
Glyphs not showing in lemonbar-xft

### ISSUE THREAD

**Issue by Quesj** [LemonBoy/bar#217]
I'm running a clean Arch install with bspwm.

So I'm really enjoying lemonbar but I can't get font awesome working. I'm using the lemonbar-xft-git version. When I try to do a little test: 

`echo -e "\uf1eb"` in terminal (Urxvt with nerd-fonts-complete "Hack:size=12") it shows the correct glyph (wifi icon). However when I try to echo it into lemonbar: 

`echo -e "\uf1eb" | lemonbar -f "Font Awesome" -f "Hack" -p` I don't see anything. 

I've added all possible font paths in /usr/share/fonts/ to my xorg.conf.

**Comment by Accurate0** [comment]
https://github.com/krypt-n/bar

This is the upstream for lemonbar-xft, you’re likely not writing out the entire font name, this may have been different but on my setup I must state “Font Awesome 5 Free” if I remember correctly.

**Comment by ALPHA-60** [comment]
@Quesj Have you tried running `lemonbar -f 'Font Awesome 5 Free Solid'`?

**Comment by NomisIV** [comment]
I can confirm `lemonbar -f 'Font Awesome 5 Free Solid'` works.
