### ISSUE TITLE
Offset doesn't seem to honor alignment direction

### ISSUE THREAD

**Issue by domsson** [LemonBoy/bar#224]
We can offset text via the `O` format option. The documentation says:

> Owidth
> Offset the current position by width pixels in the alignment direction.

I'm not quite sure what this would mean for centered text, but for left and right aligned text, I expected the offset would happen on opposite sides, respectively (either offset the left aligned text to the left and the right aligned text to the right, or vice versa).

However, this does not seem to be the case. Consider this simple example:

    echo "%{l O8}LEFT%{c O8}CENTER%{r O8}RIGHT" | lemonbar -p

The result is as follows (magnified by a factor of 2 so it is easier to inspect):

![lemonbar offset issue](https://i.imgur.com/sUe05v2.png)

I colored the left and right half of the background so it becomes easy to inspect the centered text:

![lemonbar offset issue, colored](https://i.imgur.com/85fKvlM.png)

We can see that:

- the _left aligned_ text is offset 8 pixels to the _right_
- the _center aligned_ text is offset 7 pixels to the _right_
- the _right aligned_ text is apparently not offset at all

How can this be explained?

1. I'm reading the documentation wrong
2. I'm not using the format options correctly
3. This is a bug

**Comment by domsson** [comment]
I was playing with this some more and suspect that 1. and 2. apply. In other words, I now believe I'm not using the format options correctly because I didn't understand the documentation correctly.

From what I can tell, `O` doesn't work like `B`, `F` or `T` , in that it affects the text that follows, but instead it simply adds empty space of the given amount in the exact spot you place it.

Example:

    echo "%{l O8}LEFT1%{O8}%{c O8}CENTER%{O8}%{r O8}RIGHT%{O8}" | lemonbar -p

![lemonbar with offsets](https://i.imgur.com/RIdXBJY.png)

Would be nice to know if...
- ...this is how it is supposed to work?
- ...others also interpreted the documentation like I did?

**Comment by LemonBoy** [comment]
Yes, the `oN` is handled as if a character of width `N` was drawn.
