### ISSUE TITLE
Does Lemonbar support Wayland?

### ISSUE THREAD

**Issue by Joe23232** [LemonBoy/bar#229]
I am considering using Wayland but does Lemobar work on Wayland display?

**Comment by haovipaws** [comment]
I do not believe so, because Polybar doesn't work with Wayland, I have seen [Waybar](https://github.com/Alexays/Waybar) recommended

**Comment by Joe23232** [comment]
Is Waybar closer to Polybar or Lemonbar?

**Comment by domsson** [comment]
Depends, but I'd say closer to Polybar, because where Lemonbar is just the bar, Polybar and Waybar both come as "all-in-one" package with modules/blocks already incorporated into the project.

**Comment by Joe23232** [comment]
I see, does waybar consume more ram compared to lemobar as polybar consumes
more ram compared to lemonbar?

**Comment by LemonBoy** [comment]
> Does Lemonbar support Wayland?

Nope, no plan to support it either as `lemonbar` uses xcb.
