### ISSUE TITLE
%{Sn} doesn't work as expected

### ISSUE THREAD

**Issue by echen2006** [LemonBoy/bar#231]
I have two monitors detected by `xrandr`, `eDP-1` and `DP-1-1`.  Using `%{S0}` puts the message on `DP-1-1`, and using `%{S1}` puts the message on `eDP-1`. However, the `%{Sn(xrandr monitor name)}` doesn't seem to be working, both 
```
while true;
do
echo "%{SneDP-1}test"
done | lemonbar
```
and 
```
while true;
do
echo "%{SnDP-1-1}test"
done | lemonbar
```
puts the message on monitor number 0, `DP-1-1`.

**Comment by domsson** [comment]
Just to make sure, are you running v1.4? I'm asking, because Debian, for example, is still on 1.3. You can check by running `lemonbar -h`.

**Comment by echen2006** [comment]
Nevermind, I'm using the XFT version and think it's an issue with that.
