### ISSUE TITLE
Setting default underline color at launch doesn't work

### ISSUE THREAD

**Issue by weesom** [LemonBoy/bar#233]
* `echo "%{+u}aaaaaaaaaa" | lemonbar -p -b -F "#FF0000" -U "#268bd2"` outputs everything in foreground color
* `echo "%{+u}%{U#268bd2}aaaaaaaaaa" | lemonbar -p -b -F "#FF0000" -U "#268bd2"` sets desired underline color

Man page states that it's possible to set underline color with `-U` but it doesn't seem to work for me

**Comment by LemonBoy** [comment]
You're absolutely right, I've accidentally introduced this regression in one of the recent commits.
35b0dc5 should fix the problem, please reopen the ticket if it's not working for you.

**Comment by weesom** [comment]
The issue was fixed, thank you : )
