### ISSUE TITLE
When will there be an update? 

### ISSUE THREAD

**Issue by XUnkownX** [LemonBoy/bar#248]
Hello! I absolutely love using your project, but I've noticed that it hasn't received a version update since 2020. I'm reaching out because I'm a little concerned that the project might be abandoned. When can we expect an update?

**Comment by LemonBoy** [comment]
> I'm a little concerned that the project might be abandoned.

Well, the last commit was just a few weeks ago... Anyways, release v1.5 is out, grab it while it's still hot.

https://github.com/LemonBoy/bar/releases/tag/v1.5
