### ISSUE TITLE
bar spans 2 monitors, how can I make one bar per monitor?

### ISSUE THREAD

**Issue by dncohen** [LemonBoy/bar#33]
Hi,  I've recently embraced bspwm and bar.  Loving both.  Thanks for bar!

My desktop has two monitors.  Bar is rendering one wide panel across the top of both monitors.  I'd rather see two panels, one representing each physical screen.

Hopefully that makes sense.  Any pointers how to achieve that?

**Comment by S0lll0s** [comment]
Is this the only way? It would be nice if there was a switch like `-S 3` equivalent to prepending `%{S3}`, except not drawing an empty bar onto the first monitor.
