### ISSUE TITLE
Name Conflict in Arch Community

### ISSUE THREAD

**Issue by DaveC0DE** [LemonBoy/bar#40]
https://www.archlinux.org/packages/community/any/bar/
https://aur.archlinux.org/packages/bar-aint-recursive/

There is an official 'bar' package in the Arch community repo. How about calling your thing xcbbar or something in AUR?

Here's what happens for install:
https://github.com/Spyhawk/pacaur/issues/214

**Comment by LemonBoy** [comment]
Bar has been renamed as lemonbar, problem solved.
