### ISSUE TITLE
font name handling

### ISSUE THREAD

**Issue by Evolution0** [LemonBoy/bar#80]
If a font has "," in its name it will get treated as a seperator between fonts no matter what you do to escape it.

Example:
bar -f '-_-terminusmod,icons-medium-_-normal-_-12-_-_-_-_-_-_-_'

Returns:
Could not load font -*-terminusmod

Tried single quotes, double quotes, and backslashes.

The same font worked fine in the old config.def.h.

Edit: I see the issue lies in the fact that strtok does not understand escapes.

**Comment by S0lll0s** [comment]
No other place to ask: how do I even get it to load non-"xfontesel-fonts" (idk much about X-Fonts).

I can only get it to load .pcf files via the x name (-...-...-...-...-) but no TTFs etc, even if they are installed for Xorg.
