### ISSUE TITLE
Rendering issues using vertical offset

### ISSUE THREAD

**Issue by vixus0** [LemonBoy/bar#82]
When using a vertical offset for bar (-g arg), the text is rendered with incorrect vertical padding. Refer to the following:

No offset:
![no offset](http://i.imgur.com/KWZC5XA.png)

With offset:
![with offset](http://i.imgur.com/99Z5AkX.png)

The font used in these images is available here:
https://github.com/phallus/fonts/raw/master/lemon.bdf

* I thought this might have been a font-specific issue, but I have reproduced it with various bitmap fonts.
* I have played with the height of the bar, and while this increases both the top and bottom padding, the text is still offset towards the top of the bar.

**Comment by LemonBoy** [comment]
ping
