### ISSUE TITLE
Makefile not POSIX, issues on OSX

### ISSUE THREAD

**Issue by windelicato** [LemonBoy/bar#87]
Although `install -D` is pretty convenient, it is not POSIX compliant. I cannot get this to install on OSX without some modification.

```
diff --git a/Makefile b/Makefile
index ff620a8..69a5c2a 100644
--- a/Makefile
+++ b/Makefile
@@ -32,8 +32,10 @@ clean:
        rm -f ./${EXEC}
 
 install: bar doc
-       install -D -m 755 bar ${DESTDIR}${BINDIR}/bar
-       install -D -m 644 bar.1 ${DESTDIR}${PREFIX}/share/man/man1/bar.1
+       mkdir -p  ${DESTDIR}${BINDIR}/bar
+       cp -p bar ${DESTDIR}${BINDIR}/bar
+       mkdir -p   ${DESTDIR}${PREFIX}/share/man/man1/bar.1
+       cp -p bar.1 ${DESTDIR}${PREFIX}/share/man/man1/bar.1
 
 uninstall:
        rm -f ${DESTDIR}${BINDIR}/bar
```

After it compiles successfully, I get the following and nothing shows up 
```
> echo "T" | bar -p
Could not alloc color "black"
Could not alloc color "white"
```
How would I go about debugging this?

**Comment by windelicato** [comment]
Haven't had time to dig into it yet unfortunately

**Comment by tsudoko** [comment]
The "could not allocate the color" issue happens here as well, Gentoo x86_64, i3, a9f285f

**Comment by LemonBoy** [comment]
Superseded by #143.
The change on the Makefile hasn't been backported yet, please submit a PR
