### ISSUE TITLE
bar is using 100% CPU

### ISSUE THREAD

**Issue by ninetyfourbit** [LemonBoy/bar#88]
My system has been up for 4.5 hours and for some reason the bar is starting to use 100% CPU. 

Here is the config, if that has anything to do with it: http://pastebin.com/du1BnL81

**Comment by SuperFluffy** [comment]
Are you maybe restarting the WM containing bar at some point?

I have noticed that when I kill my WM (bspwm in my case), bar does not always get killed with it. When that happens, it still runs in the background even though I have no Xorg running, and consumes 100% of CPU.

**Comment by LemonBoy** [comment]
This should have been fixed by recent commits, let me know if it's still happening
