### ISSUE TITLE
Xft Support?

### ISSUE THREAD

**Issue by baskerville** [LemonBoy/bar#9]
I would like to use anti-aliased fonts.

**Comment by bricewge** [comment]
Is it planed to merge the work of @krypt-n or does the cairo-love branch is the way to go now?

**Comment by andornaut** [comment]
I've been using krypt-n's branch for a while. So far so good. It'd be great xft support could be merged at some point.

**Comment by krypt-n** [comment]
I do not think that it should be merged:
* It is a hacky mess that probably leaks resources
* Not everyone needs/wants xft
* cairo-love works better for a lot of use cases
* transparency doesnt work

**Comment by raedwulf** [comment]
Haha, indeed the hacky mess resulted from me trying to prevent the leak of
resources - for some unknown reason Xft leaks resources.
I don't know if I managed to discover a bug or I'm simply not using it
correctly - I've tried my best several times - even to the extent of using
valgrind and examining the code deeply many times - and going through the
Xft source code.

There are reasons for using xft; if you want to be extra minimalistic and
not use cairo.  So, if someone can actually find the bug(s) in my code/xft
or the reason that xft wants to leak memory, please do tell me!  I'm
around, so if you want to work with me on this, I'll be glad to help.

On 13 February 2015 at 23:47, Krypt0n <notifications@github.com> wrote:

> I do not think that it should be merged:
>
>    - It is a hacky mess that probably leaks resources
>    - Not everyone needs/wants xft
>    - cairo-love works better for a lot of use cases
>    - transparency doesnt work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LemonBoy/bar/issues/9#issuecomment-74347469>.
>



-- 
Tai Chi Minh Ralph Eastwood
tcmreastwood@gmail.com

**Comment by raedwulf** [comment]
Oh I just realised krypt-n made a branch of this - I've been busy! krypt-n have you experienced the same bugs I have?

**Comment by LemonBoy** [comment]
I'm taking care of this in the spare time, I've cobbled together a tiny Xft replacement based on XCB. It'll probably take another (short, hopefully) while :)

**Comment by daGrevis** [comment]
What is this alternative called Cairo and where can I find it's usage examples (need something similar to bar)?

**Comment by RobertZenz** [comment]
@daGrevis Cairo is a graphics library, there is a branch/fork somewhere of bar that uses it.

**Comment by svenstaro** [comment]
@LemonBoy would love to see something get merged into mainline :)

**Comment by CestDiego** [comment]
@LemonBoy I second the +1 for xft support :D

**Comment by neo1691** [comment]
I have been following this thread since a long time, thanks @LemonBoy for keeping this alive.

**Comment by Krak-n** [comment]
Any updates on the xft front? Absolutely loving lemonbar other than that minor nitpick.

**Comment by daGrevis** [comment]
I have been using https://github.com/krypt-n/bar and works like a charm.

Consider merging Xft support into mainline.

**Comment by PureTryOut** [comment]
I was searching for Xft support, +1!

**Comment by demure** [comment]
the krypt-n/bar fork works for me as well. the main version failed to let me set any fonts at all...

**Comment by LemonBoy** [comment]
Let's put an end to this +1 fuckfest.
