### ISSUE TITLE
Some Unicode characters are not displayed

### ISSUE THREAD

**Issue by Saser** [LemonBoy/bar#93]
![2014-12-29-002909_1680x1050_scrot](https://cloud.githubusercontent.com/assets/582273/5565305/240d8f32-8ef2-11e4-9ffb-666a7614ef31.png)

It seems like some characters, even though they are included in the font, are not displayed in bar. In my screenshot I'm using Source Code Pro as primary font, and its Powerline-patched version as secondary font, on both my terminals as well as bar.

I'm outputting the characters U+2590 through U+25A4 to my bar in the top left, and the exact same string is output to a file called `do.txt` whose contents can be seen on the left terminal. It seems that any character above U+25A0 is not displayed in the bar, even though they exist in the font and are written to the file.

This seems really weird. Do you think it's a bug in bar?

**Comment by LemonBoy** [comment]
Are you using the cairo-love branch ?

**Comment by soraru** [comment]
There's even more, you can get a core dumb error if you set a font with support to japanese characters and use some of it. 
<pre>echo -e "日" | bar -p -f "-*-fixed-*-*-*-*-*-*-*-*-*-*-*-*"      
[1]    31575 done                              echo -e "日" | 
       31576 segmentation fault (core dumped)  bar -p -f "-*-fixed-*-*-*-*-*-*-*-*-*-*-*-*"</pre>

**Comment by LemonBoy** [comment]
@soraru 
The latest commit should fix the segfault, I couldn't get the kanji to show up with the fixed font

**Comment by soraru** [comment]
Thanks, that should help already.
