### ISSUE TITLE
100 % CPU usage when bar is left running after X has been killed

### ISSUE THREAD

**Issue by hersle** [LemonBoy/bar#94]
1. Start X and bar
2. Kill X (without killing bar)
3. bar consumes 100 % of the CPU

I believe the real problem is that bar continues to run when X is not running. I don't have any experience programming X, but after some experimentation I figured the problem may lie in the 

    xcb_flush(c);

call at the bottom of the main loop. Rebuilding the program with 

    if (xcb_flush(c) <= 0)
        break;

fixed the issue for me. According to documentation, this funtion returns a value <= 0 on failure. Hence I believe it sounds logical to break out of the main loop if the flush command fails. This made bar stop once X stopped, as expected.

I do not know if this is the best way to solve this issue. Therefore I leave the solution up to someone more experienced with X development.

**Comment by sible777** [comment]
I have the same issue as you, I had been looking for a solution, perhaps yours is it. I will give it a shot.

**Comment by jvvv** [comment]
One option would to add a call to xcb_connection_has_error() before the flush and break from the loop if it returns other than zero.

**Comment by LemonBoy** [comment]
Can't reproduce this here, anyway I'd be happy to see a PR with a fix (and some lines explaining why it was done) :D

**Comment by jvvv** [comment]
I can get on this later today. If no one has submitted a PR before I get to it, I should have it available in 3 to 4 hours (depending on personal stuff I need to take care of first).

**Comment by jvvv** [comment]
I've made the simple addition I mentioned above at https://github.com/jvvv/bar. I've tested it here, though to be honest, I couldn't reproduce it here either. I'm going on the idea that it might be specific to window manager, desktop environment, or some such.

If I get confirmation that it fixes this issue, I'll add explanatory comments and submit as PR.

**Comment by hersle** [comment]
It does perhaps seem to be specific to my window manager, `bspwm`.

Consider the following simplified `.xinitrc`:
```
#!/bin/bash

# Launches bspwm with bar.sh being executed as a configuration file
bspwm -c bar.sh &

# Lets it run for 5 seconds
sleep 5

# Kills X
pkill -x Xorg.bin
```

and the following `bar.sh`:
```
#!/bin/bash

# Continuously feeds bar with input
while true; do
    echo "test"
    sleep 2
done | bar-aint-recursive
```

Now execute the following commands:
```
# Starts X (will be killed after 5 seconds)
startx

# Check the CPU usage by bar
top
```

This does reproduce the issue on my machine. `top` shows `bar` with 100 % CPU usage. I believe this is a fairly common way of handling configuration files with `bspwm`.

Rebuilding `bar` with the jvvv's code addition does indeed fix this issue. Killing `X` does make the `bar.sh` script continuously complain about piping errors, although I believe this is much better than `bar` eating CPU. These piping errors can probably be fixed with simple additions to the scripts anyway.

Executing `bar.sh` independently after `bspwm` in the `.xinitrc` script like this:
```
bspwm &
bar.sh &
```
instead of having `bar.sh` executed by `bspwm` itself does seem to prevent the issue from occuring on my machine.

To make it short: `bspwm -c bar.sh &` in `.xinitrc` does lead to `bar` consuming 100 % of the CPU, while replacing it with `bspwm &; bar.sh &` does not.

This makes me uncertain whether the problem is `bspwm` and its handling of its configuration file (such as what happens to it when bspwm/X is killed) or `bar`. Perhaps the issue can be avoided altogether by modifying the scripts as well. I do, however, think that such a simple addition to code is worthwhile to prevent `bar` from eating CPU power without the user noticing it, as this seems like a very normal way to handle scripts with `bspwm`.

**Comment by jvvv** [comment]
@hersle: Thank you for testing. I'm curious about the contents of your bar.sh file. I use bspwm and run bar very similar to the example panel configs by baskerville (https://github.com/baskerville/bspwm/tree/master/examples/panel and https://github.com/baskerville/bspwm/tree/master/examples/loop) without troubles. Perhaps, after looking at you config script, someone will be able to ascertain the reason for the piping errors and/or the errors in the first place.

**Comment by jvvv** [comment]
Ok, I tested somewhat with your examples. I can't seem to replicate bar using 100% CPU. Broken pipe errors aplenty no matter what, but only if I kill X as you describe. I'll submit the PR after dinner.

**Comment by hersle** [comment]
Thank you for your attention. If you feel this fix belongs in `bar`'s source code, go for it! The code modification is very small, after all, and I'm not the only one who has experienced this problem.

**Comment by jvvv** [comment]
I apologize for not getting to this when I said I would. I became ill before I ever made it to dinner that night.

**Comment by LemonBoy** [comment]
Your health is definitely more important than bar heh, I hope you're doing well now!

**Comment by jvvv** [comment]
Thanks, much better :-)
