### ISSUE TITLE
Add support for unicode-7 characters

### ISSUE THREAD

**Issue by ZyX-I** [LemonBoy/bar#99]
I have not actually tried `bar`, but I see in your code that it uses `uint16_t` for representing a character. This obviously means that unicode code points above U+FFFF cannot be represented. If I am not mistaking  they will fall into an [else clause](https://github.com/LemonBoy/bar/blob/3b8afc6b05190e62713b27effeb087aecfbcf751/bar.c#L467) which is talking about some nonsense (“Handle ascii > 0x80”: there is no such a thing because ASCII only defines characters up to 0x7F, characters above are part of latin1 encoding if you want to have character value == unicode codepoint).

**Comment by LemonBoy** [comment]
The limitation is imposed by Xorg itself, it can't use more than 16 bits for codepoint, so this issue is a no-go (at least until I move away from server side rendering)
But you're right, that comment is incorrect, will adjust that soon :)

**Comment by ZyX-I** [comment]
@LemonBoy I would suggest to show U+FFFD REPLACEMENT CHARACTER in place of Unicode-7 characters then, not treat this as latin1.

**Comment by LemonBoy** [comment]
This should do the trick, sadly many fonts don't even have the U+FFFD character, but that's another problem

**Comment by ZyX-I** [comment]
I guess they are relying on fallbacks. I.e. there is no character in font, but either

1. fontconfig or something similar is able to take the character from some other font which has it.
2. terminal or whatever is going to display this thing has its own variant of REPLACEMENT CHARACTER (e.g. like GTK that displays big box with hexadecimal digits).

Cannot say how XCB copes with this problem.

**Comment by LemonBoy** [comment]
You should take into account that XCB doesn't even support unicode, but ucs-2
